version: '3.8'

services:
  pixel-game:
    build: 
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    # volumes:
    #   # For development, you can mount the export folder
    #   - ./export/html5:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s